# Generated by Django 4.2.3 on 2023-08-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0003_customer_groups_customer_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
