# Generated by Django 4.2.3 on 2023-08-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='eshop_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_app.customuser')),
            ],
        ),
    ]
